# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-13 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='http://blog.mtianyan.cn/', max_length=200, verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
